### ISSUE TITLE
Wireframe tweaks

### ISSUE THREAD

**Issue by jlyon** [albatrossdigital/vue-wireframes#1]
@aschmoe maybe talk about these after the 9:30 pc huddle?  I added vue-wireframes to https://waffle.io/albatrossdigital/gv2gt-toolbox.

- [x] Click Volunteer -> goes to Registration, with a link at the top, "Already have an account? Login"
- [x] Add All4Good logo (https://beta.allforgood.org/assets/images/logo-c1d181007d0d89153e780a32c2963ed9.png) on one or two Projects
- [x] Welcome Page after registration
- [x] when "Text" is checked for Preferred contact method, have text appear below, "Normal mobile messaging rates will apply."
- [x] Scroll to top when project is clicked: Scroll down list of Projects to the bottom, click Volunteer.  On the project page, you start out scrolled to the bottom.
- [x] Add search filters

Maybe:
- [x] Add a header and footer, or add a separate html page that shows it embedded?

**Comment by aschmoe** [comment]
@jlyon took care of these (added a mini footer, think its smart to leave it as minimal as possble)
